name: dart_fm_synth
description: A Dart wrapper for the libfmsynth library.
version: 0.0.1
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  ffigen: ^3.0.0
  lints: ^1.0.0
  test: ^1.16.0

ffigen:
  name: "libfmsynth"
  output: "lib/libfmsynth_generated_bindings.dart"
  llvm-path: 
    - "/usr/lib/llvm-13"
  headers:
    entry-points:
      - "libfmsynth/include/fmsynth.h"
    include-directives:
    - 'libfmsynth/include/fmsynth.h'  
  structs:
    rename:
      "_(.*)": "$1_"
    member-rename:
      ".*":
        "_(.*)": "$1_"
